# Site settings
title: Secret Escapes
locale: se

description: >
  Vi är glada att välkomna dig tillbaka med nya inspirerande reseerbjudanden. 

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/se/2020/safe-stay-policy" # the subpath of your site, e.g. /blog/
img:     "/se/2020/safe-stay-policy/_assets/img"
css:     "/se/2020/safe-stay-policy/_assets/css"
js:      "/se/2020/safe-stay-policy/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed