# Site settings
title: Secret Escapes
locale: no

description: >
  Vi ønsker deg velkommen tilbake med inspirerende reiser. Ettersom vi alle fortsatt er bekymret for COVID-19, har vi innført følgende SafeStay-retningslinjer for å hjelpe deg med å føle deg trygg på fremtidige reiser.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/no/2020/safe-stay-policy" # the subpath of your site, e.g. /blog/
img:     "/no/2020/safe-stay-policy/_assets/img"
css:     "/no/2020/safe-stay-policy/_assets/css"
js:      "/no/2020/safe-stay-policy/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed