# Site settings
title: Secret Escapes
locale: de

description: >
  We are delighted to be welcoming you back with inspiring travel deals. However, as we all remain concerned about COVID-19, the following 'Safe Stay' policies have been put in place to offer you reassurance about travel after lockdown

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/2020/safe-stay-policy" # the subpath of your site, e.g. /blog/
img:     "/de/2020/safe-stay-policy/_assets/img"
css:     "/de/2020/safe-stay-policy/_assets/css"
js:      "/de/2020/safe-stay-policy/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed